version: '2'
services:
  zk-node-01:
    image: zookeeper:3.5.5
    volumes:
      - ./bin:/apache-zookeeper-3.5.5-bin/sbin
      - ./conf:/conf
      - ./nodes/node-01/logs:/datalog
      - ./nodes/node-01:/data
    hostname: localhost
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
      - "12181:12181"
    command: /apache-zookeeper-3.5.5-bin/sbin/zkServer.sh start-foreground
  zk-node-02:
    image: zookeeper:3.5.5
    volumes:
      - ./bin:/apache-zookeeper-3.5.5-bin/sbin
      - ./conf:/conf
      - ./nodes/node-02/logs:/datalog
      - ./nodes/node-02:/data
    hostname: localhost
    ports:
      - "2182:2181"
      - "12888:2888"
      - "13888:3888"
      - "22181:12181"
    command: /apache-zookeeper-3.5.5-bin/sbin/zkServer.sh start-foreground
  zk-node-03:
    image: zookeeper:3.5.5
    volumes:
      - ./bin:/apache-zookeeper-3.5.5-bin/sbin
      - ./conf:/conf
      - ./nodes/node-03/logs:/datalog
      - ./nodes/node-03:/data
    hostname: localhost
    ports:
      - "2183:2181"
      - "32888:2888"
      - "33888:3888"
      - "32181:12181"
    command: /apache-zookeeper-3.5.5-bin/sbin/zkServer.sh start-foreground
